### ISSUE TITLE
Implement layer re-use

### ISSUE THREAD

**Issue by kvedurmu** [paketo-community/pipenv-install#12]
Could we look into implementing layer re-use in this buildpack? When building with a lockfile present, the `pipenv install` is already fairly fast (even with a lot of deps), so maybe this won't add a big difference. What I'm more interested is if it's possible to have some sort of caching between builds when building an app that does not have a Pipfile.lock present. When building an app with a bunch of dependencies in the Pipfile (see below), the initial build took 52.8 seconds to run `pipenv install` on my local macbook and a re-build took 42.5 seconds.

Example Pipfile to repro:
```
cat Pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
flask = "*"
sqlalchemy = "*"
django = "*"
anonfile = "*"
urllib3 = "*"
numpy = "*"
boto3 = "*"
botocore = "*"
six = "*"
certifi = "*"
s3transfer = "*"
python-dateutil = "*"
awscli = "*"
rsa = "*"
pyasn1 = "*"

[dev-packages]

[requires]
python_version = "3.9"
```

build logs - https://gist.github.com/kvedurmu/f07b8504f077481b646870568a349195

**Comment by arjun024** [comment]
I would imagine a user who hasn't checked-in a `Pipfile.lock` with the app expects that on every build we re-evaluate the package constraints set in the `Pipfile`.

For e.g. if `Pipfile` mentions `requests~=2.18`, the user might rebuild when they believe a new patch of `requests` is out and want to use it. Though the `Pipfile` hasn't changed, `requests~=2.18` meant `2.18.x` in the first build, and now when `2.18.x+1` is released, it refers to the latest patch. If we start caching build output based on Pipfile, then users on rebuild will be led to believe that they are using the latest patch when they are just getting an old cached version of the package.
See https://pipenv-fork.readthedocs.io/en/latest/basics.html#specifying-versions-of-a-package
I think we should not use caching to approximate correctness.
What do you think?

**Comment by kvedurmu** [comment]
That's a good call @arjun024. I think this would in practice behave similar to functionality in the Node.js buildpack's caching. So given my earlier point around how fast a pipenv install is when the lock file is present, this likely isn't high priority.

**Comment by ryanmoran** [comment]
Would `pip install` just accept an older patch version in this case just because that patch happens to be on the filesystem, or would it resolve that constraint to mean the newer patch version, thus downloading the newer version?

If the behavior is that `pip install` would always pick the newer version, then I don't see the harm in us caching these packages. We'd have saving time when there isn't a newer patch version to install, no?

**Comment by arjun024** [comment]
@ryanmoran I'm assuming you meant pip**env** install. If we were to re-use the [packages layer](https://github.com/paketo-community/pipenv-install/blob/v0.2.1/constants.go#L15-L17), we would be completely bypassing the build process and re-instating the layer from the previous build, and thus I don't see an opportunity for constraint resolution. Anything I'm missing here?
The buildpack is already using the pipenv caching based on `PIPENV_CACHE_DIR` using a separate cache layer. I looked into it and pipenv seems to be populating the layer and is available to it on the rebuild, but this doesn't seem to have a significant effect.

**Comment by ryanmoran** [comment]
There is a middle ground between re-running the build process with an empty layer and skipping the build process and reusing the layer. That middle ground is to re-run the process with a partially filled layer. This is what we do in `bundle-install` to speed up the installation of new dependencies. Could we not do something similar here so that when a user changes a single dependency they don't have to sit and wait for the buildpack to re-install the other 99 it already had from a previous build?

**Comment by arjun024** [comment]
I was looking into it, and it seems like the lion's share of time is spent on building requirements and resolving dependencies to create the lock when the lock is absent. Looking into the docs, it looks like pipenv install has a [`--skip-lock`](https://pipenv-fork.readthedocs.io/en/latest/basics.html#pipenv-install) option to bypass lock file creation and thus we can speed up the build. The only problem then is that we can't run `pipenv clean` every time because when the lock file is absent, this cmd creates the lock file first thus substantially increasing the build time.

So, it looks like the better strategy when lock is absent would be - to plug-in the packages and cache layer from the previous build, build with `--skip-lock` and then do not clean up. We can recommend in the docs that users should check-in the lock file to avoid bloat and faster builds. What you think?

**Comment by ryanmoran** [comment]
That seems reasonable. Any user that uses the "no lockfile" path can just clear their build cache to start again from a clean slate.
